platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'KKPExample' do
  pod 'kkp', :path => '../'

  pod 'Masonry', '1.1.0'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
